### ISSUE TITLE
Найти 2 функции вместо isset

### ISSUE THREAD

**Issue by insolution4** [j4s/superglobals#10]
Поскольку php-функция isset() возвращает true когда
  1. Переменная не задана (как undefined в js)
  2. Значение заданной переменной не задано (как null в js)

Нам нужны 2 функции, которые могут сделать независимую проверку для каждого из этих пунктов.

**Comment by insolution4** [comment]
Возможно с помощью array_key_exists получится сделать

**Comment by insolution4** [comment]
Возможно перехватить предупреждение об undefiend через try...catch... (или другим способом) тогда получится сделать функцию, которая определяет undefined отдельно от null

**Comment by insolution4** [comment]
(здесь http://qaru.site/questions/1365173/how-to-tell-whether-a-variable-is-null-or-undefined-in-php можно увидеть некоторые примеры для обоих комментариев выше)

**Comment by insolution4** [comment]
Также возможен вариант через get_defined_vars();

**Comment by insolution4** [comment]
Похоже что этот вариант if(!array_key_exists('Имя переменной',$_POST)){} вполне подходит для superglobals, нужно протестировать

**Comment by insolution4** [comment]
Попробуй решить задачу в таком порядке:
1. if(!array_key_exists('Имя переменной',$_POST)){}
2. get_defined_vars();
3. Возможно перехватить предупреждение об undefiend через try...catch... (или другим способом) тогда получится сделать функцию, которая определяет undefined отдельно от null

**Comment by EsfirPr** [comment]
function isUndefinedSuperglobals($value)
{
    return array_key_exists($value, $_GET) ? false : true;
}

function isNullSuperglobals($value)
{
    return array_key_exists($value, $_GET) && $_GET[$value] == '' ? true : false;
}

function isDefinedVariable($valueName)
{
    $definedVariables = array_keys(get_defined_vars());
    // return in_array($valueName, $definedVariables);
    return in_array($valueName, $definedVariables);
}

Последняя не работает из-за области видимости get_defined_vars()
